In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
# sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
# define the vocabulary size
voc_size=10000

In [5]:
# One hot representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]


In [6]:
one_hot_repr

[[5766, 2632, 8640, 7168],
 [5766, 2632, 8640, 2798],
 [5766, 5247, 8640, 6936],
 [4467, 5847, 5156, 5184, 2345],
 [4467, 5847, 5156, 5184, 8676],
 [219, 5766, 1676, 8640, 2009],
 [1807, 3539, 1086, 5184]]

In [7]:
# word embedding repr
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np


In [9]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 5766 2632 8640 7168]
 [   0    0    0    0 5766 2632 8640 2798]
 [   0    0    0    0 5766 5247 8640 6936]
 [   0    0    0 4467 5847 5156 5184 2345]
 [   0    0    0 4467 5847 5156 5184 8676]
 [   0    0    0  219 5766 1676 8640 2009]
 [   0    0    0    0 1807 3539 1086 5184]]


In [10]:
# feature representation
dim=10

In [11]:
model=Sequential()
model.add(Embedding(voc_size,dim))
model.compile('adam','mse')

In [12]:
model.predict(embedded_docs)
model.summary()

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 146ms/step


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ (7, 8, 10)             │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [13]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step


array([[[-4.13798466e-02,  3.93055789e-02,  1.19970329e-02,
          4.90284003e-02, -3.37338001e-02,  2.82076709e-02,
         -2.72620209e-02, -2.71914247e-02,  1.41306967e-03,
          3.52481045e-02],
        [-4.13798466e-02,  3.93055789e-02,  1.19970329e-02,
          4.90284003e-02, -3.37338001e-02,  2.82076709e-02,
         -2.72620209e-02, -2.71914247e-02,  1.41306967e-03,
          3.52481045e-02],
        [-4.13798466e-02,  3.93055789e-02,  1.19970329e-02,
          4.90284003e-02, -3.37338001e-02,  2.82076709e-02,
         -2.72620209e-02, -2.71914247e-02,  1.41306967e-03,
          3.52481045e-02],
        [-4.13798466e-02,  3.93055789e-02,  1.19970329e-02,
          4.90284003e-02, -3.37338001e-02,  2.82076709e-02,
         -2.72620209e-02, -2.71914247e-02,  1.41306967e-03,
          3.52481045e-02],
        [ 3.18024047e-02, -5.88046387e-03,  2.19972841e-02,
          1.91528089e-02,  3.95077504e-02,  2.80215405e-02,
          4.77946289e-02,  2.85340287e-02, -6.659783

In [14]:
embedded_docs[0]

array([   0,    0,    0,    0, 5766, 2632, 8640, 7168], dtype=int32)

In [15]:
model.predict(np.expand_dims(embedded_docs[0], axis=0))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step


array([[[-4.1379847e-02,  3.9305579e-02,  1.1997033e-02,  4.9028400e-02,
         -3.3733800e-02,  2.8207671e-02, -2.7262021e-02, -2.7191425e-02,
          1.4130697e-03,  3.5248104e-02],
        [-4.1379847e-02,  3.9305579e-02,  1.1997033e-02,  4.9028400e-02,
         -3.3733800e-02,  2.8207671e-02, -2.7262021e-02, -2.7191425e-02,
          1.4130697e-03,  3.5248104e-02],
        [-4.1379847e-02,  3.9305579e-02,  1.1997033e-02,  4.9028400e-02,
         -3.3733800e-02,  2.8207671e-02, -2.7262021e-02, -2.7191425e-02,
          1.4130697e-03,  3.5248104e-02],
        [-4.1379847e-02,  3.9305579e-02,  1.1997033e-02,  4.9028400e-02,
         -3.3733800e-02,  2.8207671e-02, -2.7262021e-02, -2.7191425e-02,
          1.4130697e-03,  3.5248104e-02],
        [ 3.1802405e-02, -5.8804639e-03,  2.1997284e-02,  1.9152809e-02,
          3.9507750e-02,  2.8021540e-02,  4.7794629e-02,  2.8534029e-02,
         -6.6597834e-03, -4.4337999e-02],
        [ 1.6983476e-02,  2.9726062e-02, -4.4949044e-02, -9.